# Generated by Django 4.1.2 on 2022-11-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uye',
            fields=[
                ('UyeID', models.AutoField(primary_key=True, serialize=False)),
                ('DiscordID', models.CharField(max_length=18, null=True, unique=True)),
                ('UyeUSERNAME', models.CharField(max_length=15, unique=True)),
                ('UyePASSWORD', models.CharField(max_length=128)),
                ('UyeEMAIL', models.EmailField(max_length=15, unique=True)),
                ('UyeWALLET', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('UyeDURUM', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Uye',
            },
        ),
    ]
