# Generated by Django 4.1.2 on 2022-11-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_uye_options_uyeacc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uyeacc',
            name='FirmaID',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='uyeacc',
            name='UyeID',
            field=models.BigIntegerField(),
        ),
    ]
