# Generated by Django 4.1.2 on 2022-11-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_uyeacc_firmaid_alter_uyeacc_uyeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UyeAdres',
            fields=[
                ('UyeAdresID', models.AutoField(primary_key=True, serialize=False)),
                ('UyeID', models.BigIntegerField()),
                ('UyeAdresBASLIK', models.CharField(max_length=50)),
                ('UyeAdresALICI', models.CharField(max_length=50)),
                ('UyeAdres', models.CharField(max_length=300)),
                ('UyeAdresALICIGSM', models.CharField(max_length=11)),
                ('UyeAdresALICITC', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'UyeAdres',
            },
        ),
    ]
