# Generated by Django 4.1.2 on 2022-11-03 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_uyeadres'),
    ]

    operations = [
        migrations.AddField(
            model_name='uyeacc',
            name='UyeAccTARIH',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
