# Generated by Django 4.1.2 on 2022-11-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_uyeacc_uyeacctarih'),
    ]

    operations = [
        migrations.AddField(
            model_name='uyeacc',
            name='UyeAccDURUM',
            field=models.BooleanField(default=False),
        ),
    ]
