# Generated by Django 4.1.2 on 2022-11-03 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_alter_uye_uyeemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UyeWalletLog',
            fields=[
                ('UyeWalletLogID', models.AutoField(primary_key=True, serialize=False)),
                ('UyeWALLET', models.DecimalField(decimal_places=2, max_digits=15)),
                ('UyeWalletLogIslem', models.CharField(choices=[('YUKLEME', 'Yükleme'), ('ALISVERIS', 'AlisVeris')], max_length=50)),
                ('UyeWalletLogAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('UyeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.uye')),
            ],
            options={
                'db_table': 'UyeWalletLog',
            },
        ),
    ]
