# Generated by Django 4.1.2 on 2022-11-03 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_uyewalletlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='uyewalletlog',
            name='UyeWalletLogTARIH',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
