# Generated by Django 4.1.2 on 2022-11-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_uyediscordlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uyediscordlog',
            name='DiscordID',
            field=models.CharField(default=11, max_length=18, unique=True),
            preserve_default=False,
        ),
    ]
