# Generated by Django 4.1.2 on 2022-11-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_alter_uyediscordlog_discordid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uyediscordlog',
            name='DiscordID',
            field=models.CharField(max_length=19, unique=True),
        ),
    ]
