# Generated by Django 4.1.2 on 2022-11-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_alter_uye_discordid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uye',
            name='DiscordID',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='uyediscordlog',
            name='DiscordID',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
