# Generated by Django 4.1.2 on 2022-11-12 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirmaApp', '0009_remove_firma_firmaresimurl'),
        ('UserApp', '0016_alter_uye_discordid_alter_uyediscordlog_discordid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UyeAccisDead',
            fields=[
                ('DeadID', models.AutoField(primary_key=True, serialize=False)),
                ('DiscordID', models.CharField(max_length=25, unique=True)),
                ('DeadDate', models.DateTimeField(auto_now_add=True)),
                ('FirmaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirmaApp.firma')),
            ],
            options={
                'db_table': 'UyeAccisDead',
            },
        ),
    ]
