# Generated by Django 4.1.2 on 2022-12-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirmaApp', '0010_apiaccess'),
        ('UserApp', '0018_alter_uyeaccisdead_discordid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uyeadres',
            name='UyeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UyeAdres', to='UserApp.uye'),
        ),
        migrations.CreateModel(
            name='UyeAlisverisLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('WalletBalance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('WalletLogAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('LogTARIH', models.DateTimeField(auto_now_add=True)),
                ('Firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirmaApp.firma')),
                ('Uye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.uye')),
            ],
            options={
                'db_table': 'UyeAlisverisLog',
            },
        ),
    ]
