# Generated by Django 4.1.2 on 2022-10-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('FirmaID', models.AutoField(primary_key=True, serialize=False)),
                ('FirmaADI', models.CharField(max_length=50)),
                ('FirmaBILGI', models.CharField(max_length=200)),
                ('FirmaEMAIL', models.CharField(max_length=50)),
                ('FirmaSIFRE', models.CharField(max_length=128)),
                ('FirmaDURUM', models.BooleanField(default=False)),
                ('FirmaRESIMURL', models.URLField()),
                ('FirmaTARIH', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Firma',
            },
        ),
    ]
