# Generated by Django 4.1.2 on 2022-10-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirmaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='FirmaYONETICI',
            field=models.CharField(default='Mehmet Slcttn', max_length=100),
            preserve_default=False,
        ),
    ]
