# Generated by Django 4.1.2 on 2022-10-31 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirmaApp', '0002_firma_firmayonetici'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discord',
            fields=[
                ('DiscordID', models.AutoField(primary_key=True, serialize=False)),
                ('DiscordANLIKUYE', models.BigIntegerField()),
                ('DiscordMAXUYE', models.BigIntegerField()),
                ('DiscordANLIKSATIS', models.BigIntegerField()),
                ('DiscordTOPSATIS', models.BigIntegerField()),
                ('DiscordTOPCALISAN', models.BigIntegerField()),
                ('DiscordANLIKCALISAN', models.BigIntegerField()),
                ('FirmaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirmaApp.firma')),
            ],
            options={
                'db_table': 'Discord',
            },
        ),
    ]
