# Generated by Django 4.1.2 on 2022-10-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirmaApp', '0003_discord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discord',
            name='FirmaID',
            field=models.BigIntegerField(),
        ),
    ]
