# Generated by Django 4.1.2 on 2022-10-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirmaApp', '0004_alter_discord_firmaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord',
            name='DiscordSupport',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
