# Generated by Django 4.1.2 on 2022-11-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirmaApp', '0005_discord_discordsupport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discord',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firmalar'},
        ),
    ]
