# Generated by Django 4.1.2 on 2022-11-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirmaApp', '0007_alter_discord_firmaid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='firma',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firmalar'},
        ),
    ]
