# Generated by Django 4.1.2 on 2022-11-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirmaApp', '0008_alter_discord_options_alter_firma_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='FirmaRESIMURL',
        ),
    ]
