# Generated by Django 4.1.2 on 2022-12-09 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirmaApp', '0009_remove_firma_firmaresimurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='apiaccess',
            fields=[
                ('apiaccessID', models.AutoField(primary_key=True, serialize=False)),
                ('API', models.CharField(choices=[('UserAuth', 'Userauth'), ('Products', 'Products')], max_length=50)),
                ('APIUrl', models.URLField()),
                ('FirmaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirmaApp.firma')),
            ],
            options={
                'db_table': 'apiaccess',
            },
        ),
    ]
